### ISSUE TITLE
Handover

### ISSUE THREAD

**Issue by SeiryuZ** [AlbertCahyawan/BIWireMob17-L6BC-1#8]
@AlbertCahyawan  do you need me to transfer this repository to your own account? You seemed still active in this repository

**Comment by SeiryuZ** [comment]
Sent the request. There's should be an email to your email address for you to accept the transfer process

**Comment by AlbertCahyawan** [comment]
Okay, received already

________________________________

**Comment by SeiryuZ** [comment]
Thanks. Good luck with whatever project you have @AlbertCahyawan
